[build-system]
requires = ["setuptools>=61.0", "setuptools-scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "pystand"
description = "Install Python versions from python-build-standalone project"
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.8"
keywords = ["python-build-standalone", "pyenv", "hatch", "pdm"]
dynamic = ["version"]
dependencies = [
  "packaging",
  "platformdirs",
  "argparse-from-file",
  "pygithub",
  "certifi",
  "filelock",
  "backports.zstd; python_version < '3.14'",
]

[[project.authors]]
name = "Mark Blakeney"
email = "mark.blakeney@bullet-systems.net"

[project.urls]
Homepage = "https://github.com/bulletmark/pystand"

[project.scripts]
pystand = "pystand:main"

[tool.setuptools_scm]
version_scheme = "post-release"

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
ignore = ["SIM115", "SIM905", "BLE001", "PLW1510", "S110", "DTZ"]

# vim:se sw=2:
